### ISSUE TITLE
Other timing options

### ISSUE THREAD

**Issue by saltsoftdrink** [ldeso/blitz#1]
Add option to turn milli seconds on or off or on when timer is less than x number of seconds

**Comment by saltsoftdrink** [comment]
Also, add different modes

**Comment by ldeso** [comment]
Thanks for your suggestions. As for now I have neither enough time nor knowledge to implement a user interface, I prefer to keep the app minimal and refrain from adding functionalities like other timing options. Feel free to propose ideas on how the user interface could be implemented for this and I will consider reopening this issue.

**Resources**
- [Time Systems at Sensei's Library](https://senseis.xmp.net/?TimeSystem)
- [Which timing options do DGT clocks have?](https://web.archive.org/web/20240907080130oe_/https://s3.eu-central-1.amazonaws.com/digital-game-technology-2021/media/Products/Chess-Clocks/AWD_Clock-Choice-guide_V1.5.pdf)
